In [1]:
from traj2sim import *
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline


In [7]:
def sphere_point(theta, phi):
    return [math.sin(phi)*math.cos(theta), math.sin(phi)*math.sin(theta), -math.cos(phi)]

def great_circle_with_time(theta, length=10, noise=False, sigma=0.05, time_i=0, time_f=10):
    traj = np.zeros((time_f-time_i,4))
    for i in range(0, time_f-time_i):
        traj[i][1:] = sphere_point(theta, (time_i+i)*math.pi/length)
        traj[i][0] = sphere_point(theta, (time_i+i)*math.pi/length)[2]
        if noise == True:
            traj[i][1:] = np.add(traj[i],sigma*np.random.randn(1,3))
    return traj

l=300
traj1 = great_circle_with_time(2*math.pi*0.1, length=l, time_f=l)
traj2 = great_circle_with_time(2*math.pi*0.6, length=l, time_f=l)
traj3 = great_circle_with_time(2*math.pi*0.5, length=l, time_f=l)

In [ ]:
t2s = Traj2Sim()
t2s.set_trajectories([traj1, traj2, traj3])
t2s.compute_mssd()

print(t2s.bifilt)

#Length of each trajectory vs Time taken (s)
#100 - 2.2
#200 - 8.2
#300 - 18.2
#400 - 32
#500 - 52
#600 - 77
#1000 - 200
#2000 - 840
#Time complexity looks quadratic in length of each trajectory, as expected.
#Average complexity: O(n^2), Worst case amortized complexity: O(n^4)

In [4]:
t2s.save_bifilt(filename='t2s_test_bifilt.npy')
t2s = Traj2Sim()
t2s.load_bifilt(filename='t2s_test_bifilt.npy')
print(t2s.bifilt)


[[[0.    0.313 0.618]
  [0.313 0.    0.363]
  [0.618 0.363 0.   ]]

 [[0.    0.908 1.134]
  [0.908 0.    0.5  ]
  [1.134 0.5   0.   ]]

 [[0.    1.414 1.551]
  [1.414 0.    0.588]
  [1.551 0.588 0.   ]]

 [[0.    1.782 1.819]
  [1.782 0.    0.618]
  [1.819 0.618 0.   ]]

 [[0.    1.975 1.881]
  [1.975 0.    0.618]
  [1.881 0.618 0.   ]]

 [[0.    1.975 1.881]
  [1.975 0.    0.618]
  [1.881 0.618 0.   ]]

 [[0.    1.975 1.881]
  [1.975 0.    0.618]
  [1.881 0.618 0.   ]]

 [[0.    1.975 1.912]
  [1.975 0.    0.679]
  [1.912 0.679 0.   ]]]
